baseURL = 'https://seyoungjeong.github.io/'
languageCode = 'ko-KR'
title = 'Off Piste'
theme = 'PaperMod'

[author]
  name = "Seyoung Jeong"

[params]
  defaultTheme = 'auto'
  author = "Seyoung Jeong"
