baseURL = 'https://seyoungjeong.github.io/'
relativeURLs = true
languageCode = 'ko-KR'
title = 'Off Piste'
theme = 'PaperMod'

[author]
  name = "Seyoung Jeong"

[params]
  defaultTheme = 'auto'
  author = "Seyoung Jeong"

[[menu.main]]
  identifier = "categories"
  name = "Categories"
  url = "/categories/"
  weight = 10

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 20
