[build]
  publish = "public"
  command = "git submodule update --init --recursive && hugo --gc --minify --config config.toml"

[context.production.environment]
  HUGO_VERSION = "0.156.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
