#title in header
title: "Seyoung Jeong"

#main info
#owner
owner: "Hey! I'm Seyoung"
email: #test@test.test
info: "Embedded software engineer, tech blogger, and open source enthusiast."
#description
desc: "Welcome to my blog. My full name is Seokyoung, but I foten go by Seyoung or Seo. I'm writing in English and Korean about development, programming, and other tech-related topics. Enjoy your stay!"

#menu
menu:
  About: /About
  Projects: /Projects
  Anything-Else: /Anything-Else

#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: false
placename: Earth
placelink: https://en.wikipedia.org/wiki/Earth
github: https://github.com/adisaktijrs
linkedin: https://linkedin.com/in/adisaktijrs
twitter: https://twitter.com/adisaktijrs
instagram: https://instagram.com/adisaktijrs

# Misc
nanobar: /js/nanobar.min.js
switch_light: ‚òÄÔ∏è
switch_dark: üåë

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io
